/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
	"time"
)

// checks if the ProjectFullListDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectFullListDto{}

// ProjectFullListDto struct for ProjectFullListDto
type ProjectFullListDto struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Operation *string `json:"operation,omitempty"`
	JobUrl *string `json:"jobUrl,omitempty"`
	ImageName *string `json:"imageName,omitempty"`
	Token *string `json:"token,omitempty"`
	IsKubernetes *bool `json:"isKubernetes,omitempty"`
	IsLocked *bool `json:"isLocked,omitempty"`
	IsBackupEnabled *bool `json:"isBackupEnabled,omitempty"`
	IsMonitoringEnabled *bool `json:"isMonitoringEnabled,omitempty"`
	IsAutoUpgrade *bool `json:"isAutoUpgrade,omitempty"`
	AccessProfileRevision *int32 `json:"accessProfileRevision,omitempty"`
	CloudCredentialName *string `json:"cloudCredentialName,omitempty"`
	OrganizationName *string `json:"organizationName,omitempty"`
	OrganizationId *int32 `json:"organizationId,omitempty"`
	Status *string `json:"status,omitempty"`
	Health *string `json:"health,omitempty"`
	AccessIp *string `json:"accessIp,omitempty"`
	CloudType *string `json:"cloudType,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	AccessProfiles *AccessProfilesForProjectListDto `json:"accessProfiles,omitempty"`
	IsDeleteCluster *bool `json:"isDeleteCluster,omitempty"`
	TaikunPrivateSSHKey *string `json:"taikunPrivateSSHKey,omitempty"`
	TaikunPublicSSHKey *string `json:"taikunPublicSSHKey,omitempty"`
	StandaloneVms []StandAloneVmFullDto `json:"standaloneVms,omitempty"`
	Cidr *string `json:"cidr,omitempty"`
	NetMask *int32 `json:"netMask,omitempty"`
	PrivateIp *string `json:"privateIp,omitempty"`
	PublicIp *string `json:"publicIp,omitempty"`
	IsKubevapEnabled *bool `json:"isKubevapEnabled,omitempty"`
	TanzuReleaseVersion *string `json:"tanzuReleaseVersion,omitempty"`
}

// NewProjectFullListDto instantiates a new ProjectFullListDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectFullListDto() *ProjectFullListDto {
	this := ProjectFullListDto{}
	return &this
}

// NewProjectFullListDtoWithDefaults instantiates a new ProjectFullListDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectFullListDtoWithDefaults() *ProjectFullListDto {
	this := ProjectFullListDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProjectFullListDto) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectFullListDto) SetName(v string) {
	o.Name = &v
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *ProjectFullListDto) SetOperation(v string) {
	o.Operation = &v
}

// GetJobUrl returns the JobUrl field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetJobUrl() string {
	if o == nil || IsNil(o.JobUrl) {
		var ret string
		return ret
	}
	return *o.JobUrl
}

// GetJobUrlOk returns a tuple with the JobUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetJobUrlOk() (*string, bool) {
	if o == nil || IsNil(o.JobUrl) {
		return nil, false
	}
	return o.JobUrl, true
}

// HasJobUrl returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasJobUrl() bool {
	if o != nil && !IsNil(o.JobUrl) {
		return true
	}

	return false
}

// SetJobUrl gets a reference to the given string and assigns it to the JobUrl field.
func (o *ProjectFullListDto) SetJobUrl(v string) {
	o.JobUrl = &v
}

// GetImageName returns the ImageName field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetImageName() string {
	if o == nil || IsNil(o.ImageName) {
		var ret string
		return ret
	}
	return *o.ImageName
}

// GetImageNameOk returns a tuple with the ImageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetImageNameOk() (*string, bool) {
	if o == nil || IsNil(o.ImageName) {
		return nil, false
	}
	return o.ImageName, true
}

// HasImageName returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasImageName() bool {
	if o != nil && !IsNil(o.ImageName) {
		return true
	}

	return false
}

// SetImageName gets a reference to the given string and assigns it to the ImageName field.
func (o *ProjectFullListDto) SetImageName(v string) {
	o.ImageName = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ProjectFullListDto) SetToken(v string) {
	o.Token = &v
}

// GetIsKubernetes returns the IsKubernetes field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsKubernetes() bool {
	if o == nil || IsNil(o.IsKubernetes) {
		var ret bool
		return ret
	}
	return *o.IsKubernetes
}

// GetIsKubernetesOk returns a tuple with the IsKubernetes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsKubernetesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsKubernetes) {
		return nil, false
	}
	return o.IsKubernetes, true
}

// HasIsKubernetes returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsKubernetes() bool {
	if o != nil && !IsNil(o.IsKubernetes) {
		return true
	}

	return false
}

// SetIsKubernetes gets a reference to the given bool and assigns it to the IsKubernetes field.
func (o *ProjectFullListDto) SetIsKubernetes(v bool) {
	o.IsKubernetes = &v
}

// GetIsLocked returns the IsLocked field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsLocked() bool {
	if o == nil || IsNil(o.IsLocked) {
		var ret bool
		return ret
	}
	return *o.IsLocked
}

// GetIsLockedOk returns a tuple with the IsLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLocked) {
		return nil, false
	}
	return o.IsLocked, true
}

// HasIsLocked returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsLocked() bool {
	if o != nil && !IsNil(o.IsLocked) {
		return true
	}

	return false
}

// SetIsLocked gets a reference to the given bool and assigns it to the IsLocked field.
func (o *ProjectFullListDto) SetIsLocked(v bool) {
	o.IsLocked = &v
}

// GetIsBackupEnabled returns the IsBackupEnabled field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsBackupEnabled() bool {
	if o == nil || IsNil(o.IsBackupEnabled) {
		var ret bool
		return ret
	}
	return *o.IsBackupEnabled
}

// GetIsBackupEnabledOk returns a tuple with the IsBackupEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsBackupEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBackupEnabled) {
		return nil, false
	}
	return o.IsBackupEnabled, true
}

// HasIsBackupEnabled returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsBackupEnabled() bool {
	if o != nil && !IsNil(o.IsBackupEnabled) {
		return true
	}

	return false
}

// SetIsBackupEnabled gets a reference to the given bool and assigns it to the IsBackupEnabled field.
func (o *ProjectFullListDto) SetIsBackupEnabled(v bool) {
	o.IsBackupEnabled = &v
}

// GetIsMonitoringEnabled returns the IsMonitoringEnabled field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsMonitoringEnabled() bool {
	if o == nil || IsNil(o.IsMonitoringEnabled) {
		var ret bool
		return ret
	}
	return *o.IsMonitoringEnabled
}

// GetIsMonitoringEnabledOk returns a tuple with the IsMonitoringEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsMonitoringEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMonitoringEnabled) {
		return nil, false
	}
	return o.IsMonitoringEnabled, true
}

// HasIsMonitoringEnabled returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsMonitoringEnabled() bool {
	if o != nil && !IsNil(o.IsMonitoringEnabled) {
		return true
	}

	return false
}

// SetIsMonitoringEnabled gets a reference to the given bool and assigns it to the IsMonitoringEnabled field.
func (o *ProjectFullListDto) SetIsMonitoringEnabled(v bool) {
	o.IsMonitoringEnabled = &v
}

// GetIsAutoUpgrade returns the IsAutoUpgrade field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsAutoUpgrade() bool {
	if o == nil || IsNil(o.IsAutoUpgrade) {
		var ret bool
		return ret
	}
	return *o.IsAutoUpgrade
}

// GetIsAutoUpgradeOk returns a tuple with the IsAutoUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsAutoUpgradeOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutoUpgrade) {
		return nil, false
	}
	return o.IsAutoUpgrade, true
}

// HasIsAutoUpgrade returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsAutoUpgrade() bool {
	if o != nil && !IsNil(o.IsAutoUpgrade) {
		return true
	}

	return false
}

// SetIsAutoUpgrade gets a reference to the given bool and assigns it to the IsAutoUpgrade field.
func (o *ProjectFullListDto) SetIsAutoUpgrade(v bool) {
	o.IsAutoUpgrade = &v
}

// GetAccessProfileRevision returns the AccessProfileRevision field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetAccessProfileRevision() int32 {
	if o == nil || IsNil(o.AccessProfileRevision) {
		var ret int32
		return ret
	}
	return *o.AccessProfileRevision
}

// GetAccessProfileRevisionOk returns a tuple with the AccessProfileRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetAccessProfileRevisionOk() (*int32, bool) {
	if o == nil || IsNil(o.AccessProfileRevision) {
		return nil, false
	}
	return o.AccessProfileRevision, true
}

// HasAccessProfileRevision returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasAccessProfileRevision() bool {
	if o != nil && !IsNil(o.AccessProfileRevision) {
		return true
	}

	return false
}

// SetAccessProfileRevision gets a reference to the given int32 and assigns it to the AccessProfileRevision field.
func (o *ProjectFullListDto) SetAccessProfileRevision(v int32) {
	o.AccessProfileRevision = &v
}

// GetCloudCredentialName returns the CloudCredentialName field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetCloudCredentialName() string {
	if o == nil || IsNil(o.CloudCredentialName) {
		var ret string
		return ret
	}
	return *o.CloudCredentialName
}

// GetCloudCredentialNameOk returns a tuple with the CloudCredentialName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetCloudCredentialNameOk() (*string, bool) {
	if o == nil || IsNil(o.CloudCredentialName) {
		return nil, false
	}
	return o.CloudCredentialName, true
}

// HasCloudCredentialName returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasCloudCredentialName() bool {
	if o != nil && !IsNil(o.CloudCredentialName) {
		return true
	}

	return false
}

// SetCloudCredentialName gets a reference to the given string and assigns it to the CloudCredentialName field.
func (o *ProjectFullListDto) SetCloudCredentialName(v string) {
	o.CloudCredentialName = &v
}

// GetOrganizationName returns the OrganizationName field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetOrganizationName() string {
	if o == nil || IsNil(o.OrganizationName) {
		var ret string
		return ret
	}
	return *o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetOrganizationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationName) {
		return nil, false
	}
	return o.OrganizationName, true
}

// HasOrganizationName returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasOrganizationName() bool {
	if o != nil && !IsNil(o.OrganizationName) {
		return true
	}

	return false
}

// SetOrganizationName gets a reference to the given string and assigns it to the OrganizationName field.
func (o *ProjectFullListDto) SetOrganizationName(v string) {
	o.OrganizationName = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *ProjectFullListDto) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ProjectFullListDto) SetStatus(v string) {
	o.Status = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetHealth() string {
	if o == nil || IsNil(o.Health) {
		var ret string
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetHealthOk() (*string, bool) {
	if o == nil || IsNil(o.Health) {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasHealth() bool {
	if o != nil && !IsNil(o.Health) {
		return true
	}

	return false
}

// SetHealth gets a reference to the given string and assigns it to the Health field.
func (o *ProjectFullListDto) SetHealth(v string) {
	o.Health = &v
}

// GetAccessIp returns the AccessIp field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetAccessIp() string {
	if o == nil || IsNil(o.AccessIp) {
		var ret string
		return ret
	}
	return *o.AccessIp
}

// GetAccessIpOk returns a tuple with the AccessIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetAccessIpOk() (*string, bool) {
	if o == nil || IsNil(o.AccessIp) {
		return nil, false
	}
	return o.AccessIp, true
}

// HasAccessIp returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasAccessIp() bool {
	if o != nil && !IsNil(o.AccessIp) {
		return true
	}

	return false
}

// SetAccessIp gets a reference to the given string and assigns it to the AccessIp field.
func (o *ProjectFullListDto) SetAccessIp(v string) {
	o.AccessIp = &v
}

// GetCloudType returns the CloudType field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetCloudType() string {
	if o == nil || IsNil(o.CloudType) {
		var ret string
		return ret
	}
	return *o.CloudType
}

// GetCloudTypeOk returns a tuple with the CloudType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetCloudTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CloudType) {
		return nil, false
	}
	return o.CloudType, true
}

// HasCloudType returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasCloudType() bool {
	if o != nil && !IsNil(o.CloudType) {
		return true
	}

	return false
}

// SetCloudType gets a reference to the given string and assigns it to the CloudType field.
func (o *ProjectFullListDto) SetCloudType(v string) {
	o.CloudType = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ProjectFullListDto) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProjectFullListDto) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetAccessProfiles returns the AccessProfiles field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetAccessProfiles() AccessProfilesForProjectListDto {
	if o == nil || IsNil(o.AccessProfiles) {
		var ret AccessProfilesForProjectListDto
		return ret
	}
	return *o.AccessProfiles
}

// GetAccessProfilesOk returns a tuple with the AccessProfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetAccessProfilesOk() (*AccessProfilesForProjectListDto, bool) {
	if o == nil || IsNil(o.AccessProfiles) {
		return nil, false
	}
	return o.AccessProfiles, true
}

// HasAccessProfiles returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasAccessProfiles() bool {
	if o != nil && !IsNil(o.AccessProfiles) {
		return true
	}

	return false
}

// SetAccessProfiles gets a reference to the given AccessProfilesForProjectListDto and assigns it to the AccessProfiles field.
func (o *ProjectFullListDto) SetAccessProfiles(v AccessProfilesForProjectListDto) {
	o.AccessProfiles = &v
}

// GetIsDeleteCluster returns the IsDeleteCluster field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsDeleteCluster() bool {
	if o == nil || IsNil(o.IsDeleteCluster) {
		var ret bool
		return ret
	}
	return *o.IsDeleteCluster
}

// GetIsDeleteClusterOk returns a tuple with the IsDeleteCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsDeleteClusterOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleteCluster) {
		return nil, false
	}
	return o.IsDeleteCluster, true
}

// HasIsDeleteCluster returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsDeleteCluster() bool {
	if o != nil && !IsNil(o.IsDeleteCluster) {
		return true
	}

	return false
}

// SetIsDeleteCluster gets a reference to the given bool and assigns it to the IsDeleteCluster field.
func (o *ProjectFullListDto) SetIsDeleteCluster(v bool) {
	o.IsDeleteCluster = &v
}

// GetTaikunPrivateSSHKey returns the TaikunPrivateSSHKey field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetTaikunPrivateSSHKey() string {
	if o == nil || IsNil(o.TaikunPrivateSSHKey) {
		var ret string
		return ret
	}
	return *o.TaikunPrivateSSHKey
}

// GetTaikunPrivateSSHKeyOk returns a tuple with the TaikunPrivateSSHKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetTaikunPrivateSSHKeyOk() (*string, bool) {
	if o == nil || IsNil(o.TaikunPrivateSSHKey) {
		return nil, false
	}
	return o.TaikunPrivateSSHKey, true
}

// HasTaikunPrivateSSHKey returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasTaikunPrivateSSHKey() bool {
	if o != nil && !IsNil(o.TaikunPrivateSSHKey) {
		return true
	}

	return false
}

// SetTaikunPrivateSSHKey gets a reference to the given string and assigns it to the TaikunPrivateSSHKey field.
func (o *ProjectFullListDto) SetTaikunPrivateSSHKey(v string) {
	o.TaikunPrivateSSHKey = &v
}

// GetTaikunPublicSSHKey returns the TaikunPublicSSHKey field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetTaikunPublicSSHKey() string {
	if o == nil || IsNil(o.TaikunPublicSSHKey) {
		var ret string
		return ret
	}
	return *o.TaikunPublicSSHKey
}

// GetTaikunPublicSSHKeyOk returns a tuple with the TaikunPublicSSHKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetTaikunPublicSSHKeyOk() (*string, bool) {
	if o == nil || IsNil(o.TaikunPublicSSHKey) {
		return nil, false
	}
	return o.TaikunPublicSSHKey, true
}

// HasTaikunPublicSSHKey returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasTaikunPublicSSHKey() bool {
	if o != nil && !IsNil(o.TaikunPublicSSHKey) {
		return true
	}

	return false
}

// SetTaikunPublicSSHKey gets a reference to the given string and assigns it to the TaikunPublicSSHKey field.
func (o *ProjectFullListDto) SetTaikunPublicSSHKey(v string) {
	o.TaikunPublicSSHKey = &v
}

// GetStandaloneVms returns the StandaloneVms field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetStandaloneVms() []StandAloneVmFullDto {
	if o == nil || IsNil(o.StandaloneVms) {
		var ret []StandAloneVmFullDto
		return ret
	}
	return o.StandaloneVms
}

// GetStandaloneVmsOk returns a tuple with the StandaloneVms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetStandaloneVmsOk() ([]StandAloneVmFullDto, bool) {
	if o == nil || IsNil(o.StandaloneVms) {
		return nil, false
	}
	return o.StandaloneVms, true
}

// HasStandaloneVms returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasStandaloneVms() bool {
	if o != nil && !IsNil(o.StandaloneVms) {
		return true
	}

	return false
}

// SetStandaloneVms gets a reference to the given []StandAloneVmFullDto and assigns it to the StandaloneVms field.
func (o *ProjectFullListDto) SetStandaloneVms(v []StandAloneVmFullDto) {
	o.StandaloneVms = v
}

// GetCidr returns the Cidr field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetCidr() string {
	if o == nil || IsNil(o.Cidr) {
		var ret string
		return ret
	}
	return *o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetCidrOk() (*string, bool) {
	if o == nil || IsNil(o.Cidr) {
		return nil, false
	}
	return o.Cidr, true
}

// HasCidr returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasCidr() bool {
	if o != nil && !IsNil(o.Cidr) {
		return true
	}

	return false
}

// SetCidr gets a reference to the given string and assigns it to the Cidr field.
func (o *ProjectFullListDto) SetCidr(v string) {
	o.Cidr = &v
}

// GetNetMask returns the NetMask field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetNetMask() int32 {
	if o == nil || IsNil(o.NetMask) {
		var ret int32
		return ret
	}
	return *o.NetMask
}

// GetNetMaskOk returns a tuple with the NetMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetNetMaskOk() (*int32, bool) {
	if o == nil || IsNil(o.NetMask) {
		return nil, false
	}
	return o.NetMask, true
}

// HasNetMask returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasNetMask() bool {
	if o != nil && !IsNil(o.NetMask) {
		return true
	}

	return false
}

// SetNetMask gets a reference to the given int32 and assigns it to the NetMask field.
func (o *ProjectFullListDto) SetNetMask(v int32) {
	o.NetMask = &v
}

// GetPrivateIp returns the PrivateIp field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetPrivateIp() string {
	if o == nil || IsNil(o.PrivateIp) {
		var ret string
		return ret
	}
	return *o.PrivateIp
}

// GetPrivateIpOk returns a tuple with the PrivateIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetPrivateIpOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateIp) {
		return nil, false
	}
	return o.PrivateIp, true
}

// HasPrivateIp returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasPrivateIp() bool {
	if o != nil && !IsNil(o.PrivateIp) {
		return true
	}

	return false
}

// SetPrivateIp gets a reference to the given string and assigns it to the PrivateIp field.
func (o *ProjectFullListDto) SetPrivateIp(v string) {
	o.PrivateIp = &v
}

// GetPublicIp returns the PublicIp field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetPublicIp() string {
	if o == nil || IsNil(o.PublicIp) {
		var ret string
		return ret
	}
	return *o.PublicIp
}

// GetPublicIpOk returns a tuple with the PublicIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetPublicIpOk() (*string, bool) {
	if o == nil || IsNil(o.PublicIp) {
		return nil, false
	}
	return o.PublicIp, true
}

// HasPublicIp returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasPublicIp() bool {
	if o != nil && !IsNil(o.PublicIp) {
		return true
	}

	return false
}

// SetPublicIp gets a reference to the given string and assigns it to the PublicIp field.
func (o *ProjectFullListDto) SetPublicIp(v string) {
	o.PublicIp = &v
}

// GetIsKubevapEnabled returns the IsKubevapEnabled field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetIsKubevapEnabled() bool {
	if o == nil || IsNil(o.IsKubevapEnabled) {
		var ret bool
		return ret
	}
	return *o.IsKubevapEnabled
}

// GetIsKubevapEnabledOk returns a tuple with the IsKubevapEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetIsKubevapEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsKubevapEnabled) {
		return nil, false
	}
	return o.IsKubevapEnabled, true
}

// HasIsKubevapEnabled returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasIsKubevapEnabled() bool {
	if o != nil && !IsNil(o.IsKubevapEnabled) {
		return true
	}

	return false
}

// SetIsKubevapEnabled gets a reference to the given bool and assigns it to the IsKubevapEnabled field.
func (o *ProjectFullListDto) SetIsKubevapEnabled(v bool) {
	o.IsKubevapEnabled = &v
}

// GetTanzuReleaseVersion returns the TanzuReleaseVersion field value if set, zero value otherwise.
func (o *ProjectFullListDto) GetTanzuReleaseVersion() string {
	if o == nil || IsNil(o.TanzuReleaseVersion) {
		var ret string
		return ret
	}
	return *o.TanzuReleaseVersion
}

// GetTanzuReleaseVersionOk returns a tuple with the TanzuReleaseVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectFullListDto) GetTanzuReleaseVersionOk() (*string, bool) {
	if o == nil || IsNil(o.TanzuReleaseVersion) {
		return nil, false
	}
	return o.TanzuReleaseVersion, true
}

// HasTanzuReleaseVersion returns a boolean if a field has been set.
func (o *ProjectFullListDto) HasTanzuReleaseVersion() bool {
	if o != nil && !IsNil(o.TanzuReleaseVersion) {
		return true
	}

	return false
}

// SetTanzuReleaseVersion gets a reference to the given string and assigns it to the TanzuReleaseVersion field.
func (o *ProjectFullListDto) SetTanzuReleaseVersion(v string) {
	o.TanzuReleaseVersion = &v
}

func (o ProjectFullListDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectFullListDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	if !IsNil(o.JobUrl) {
		toSerialize["jobUrl"] = o.JobUrl
	}
	if !IsNil(o.ImageName) {
		toSerialize["imageName"] = o.ImageName
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.IsKubernetes) {
		toSerialize["isKubernetes"] = o.IsKubernetes
	}
	if !IsNil(o.IsLocked) {
		toSerialize["isLocked"] = o.IsLocked
	}
	if !IsNil(o.IsBackupEnabled) {
		toSerialize["isBackupEnabled"] = o.IsBackupEnabled
	}
	if !IsNil(o.IsMonitoringEnabled) {
		toSerialize["isMonitoringEnabled"] = o.IsMonitoringEnabled
	}
	if !IsNil(o.IsAutoUpgrade) {
		toSerialize["isAutoUpgrade"] = o.IsAutoUpgrade
	}
	if !IsNil(o.AccessProfileRevision) {
		toSerialize["accessProfileRevision"] = o.AccessProfileRevision
	}
	if !IsNil(o.CloudCredentialName) {
		toSerialize["cloudCredentialName"] = o.CloudCredentialName
	}
	if !IsNil(o.OrganizationName) {
		toSerialize["organizationName"] = o.OrganizationName
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Health) {
		toSerialize["health"] = o.Health
	}
	if !IsNil(o.AccessIp) {
		toSerialize["accessIp"] = o.AccessIp
	}
	if !IsNil(o.CloudType) {
		toSerialize["cloudType"] = o.CloudType
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.AccessProfiles) {
		toSerialize["accessProfiles"] = o.AccessProfiles
	}
	if !IsNil(o.IsDeleteCluster) {
		toSerialize["isDeleteCluster"] = o.IsDeleteCluster
	}
	if !IsNil(o.TaikunPrivateSSHKey) {
		toSerialize["taikunPrivateSSHKey"] = o.TaikunPrivateSSHKey
	}
	if !IsNil(o.TaikunPublicSSHKey) {
		toSerialize["taikunPublicSSHKey"] = o.TaikunPublicSSHKey
	}
	if !IsNil(o.StandaloneVms) {
		toSerialize["standaloneVms"] = o.StandaloneVms
	}
	if !IsNil(o.Cidr) {
		toSerialize["cidr"] = o.Cidr
	}
	if !IsNil(o.NetMask) {
		toSerialize["netMask"] = o.NetMask
	}
	if !IsNil(o.PrivateIp) {
		toSerialize["privateIp"] = o.PrivateIp
	}
	if !IsNil(o.PublicIp) {
		toSerialize["publicIp"] = o.PublicIp
	}
	if !IsNil(o.IsKubevapEnabled) {
		toSerialize["isKubevapEnabled"] = o.IsKubevapEnabled
	}
	if !IsNil(o.TanzuReleaseVersion) {
		toSerialize["tanzuReleaseVersion"] = o.TanzuReleaseVersion
	}
	return toSerialize, nil
}

type NullableProjectFullListDto struct {
	value *ProjectFullListDto
	isSet bool
}

func (v NullableProjectFullListDto) Get() *ProjectFullListDto {
	return v.value
}

func (v *NullableProjectFullListDto) Set(val *ProjectFullListDto) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectFullListDto) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectFullListDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectFullListDto(val *ProjectFullListDto) *NullableProjectFullListDto {
	return &NullableProjectFullListDto{value: val, isSet: true}
}

func (v NullableProjectFullListDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectFullListDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


