/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@itera.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the ProjectActionUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectActionUpdateDto{}

// ProjectActionUpdateDto struct for ProjectActionUpdateDto
type ProjectActionUpdateDto struct {
	Operation *string `json:"operation,omitempty"`
	JobUrl *string `json:"jobUrl,omitempty"`
	EstimatedTime *string `json:"estimatedTime,omitempty"`
}

// NewProjectActionUpdateDto instantiates a new ProjectActionUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectActionUpdateDto() *ProjectActionUpdateDto {
	this := ProjectActionUpdateDto{}
	return &this
}

// NewProjectActionUpdateDtoWithDefaults instantiates a new ProjectActionUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectActionUpdateDtoWithDefaults() *ProjectActionUpdateDto {
	this := ProjectActionUpdateDto{}
	return &this
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *ProjectActionUpdateDto) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectActionUpdateDto) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *ProjectActionUpdateDto) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *ProjectActionUpdateDto) SetOperation(v string) {
	o.Operation = &v
}

// GetJobUrl returns the JobUrl field value if set, zero value otherwise.
func (o *ProjectActionUpdateDto) GetJobUrl() string {
	if o == nil || IsNil(o.JobUrl) {
		var ret string
		return ret
	}
	return *o.JobUrl
}

// GetJobUrlOk returns a tuple with the JobUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectActionUpdateDto) GetJobUrlOk() (*string, bool) {
	if o == nil || IsNil(o.JobUrl) {
		return nil, false
	}
	return o.JobUrl, true
}

// HasJobUrl returns a boolean if a field has been set.
func (o *ProjectActionUpdateDto) HasJobUrl() bool {
	if o != nil && !IsNil(o.JobUrl) {
		return true
	}

	return false
}

// SetJobUrl gets a reference to the given string and assigns it to the JobUrl field.
func (o *ProjectActionUpdateDto) SetJobUrl(v string) {
	o.JobUrl = &v
}

// GetEstimatedTime returns the EstimatedTime field value if set, zero value otherwise.
func (o *ProjectActionUpdateDto) GetEstimatedTime() string {
	if o == nil || IsNil(o.EstimatedTime) {
		var ret string
		return ret
	}
	return *o.EstimatedTime
}

// GetEstimatedTimeOk returns a tuple with the EstimatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectActionUpdateDto) GetEstimatedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedTime) {
		return nil, false
	}
	return o.EstimatedTime, true
}

// HasEstimatedTime returns a boolean if a field has been set.
func (o *ProjectActionUpdateDto) HasEstimatedTime() bool {
	if o != nil && !IsNil(o.EstimatedTime) {
		return true
	}

	return false
}

// SetEstimatedTime gets a reference to the given string and assigns it to the EstimatedTime field.
func (o *ProjectActionUpdateDto) SetEstimatedTime(v string) {
	o.EstimatedTime = &v
}

func (o ProjectActionUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectActionUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	if !IsNil(o.JobUrl) {
		toSerialize["jobUrl"] = o.JobUrl
	}
	if !IsNil(o.EstimatedTime) {
		toSerialize["estimatedTime"] = o.EstimatedTime
	}
	return toSerialize, nil
}

type NullableProjectActionUpdateDto struct {
	value *ProjectActionUpdateDto
	isSet bool
}

func (v NullableProjectActionUpdateDto) Get() *ProjectActionUpdateDto {
	return v.value
}

func (v *NullableProjectActionUpdateDto) Set(val *ProjectActionUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectActionUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectActionUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectActionUpdateDto(val *ProjectActionUpdateDto) *NullableProjectActionUpdateDto {
	return &NullableProjectActionUpdateDto{value: val, isSet: true}
}

func (v NullableProjectActionUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectActionUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


