/*
Taikun - WebApi

Testing AlertingIntegrationsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package taikuncore

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/chnyda/taikungoclient"
)

func Test_taikuncore_AlertingIntegrationsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AlertingIntegrationsApiService AlertingIntegrationsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var v string

		resp, httpRes, err := apiClient.AlertingIntegrationsApi.AlertingIntegrationsCreate(context.Background(), v).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertingIntegrationsApiService AlertingIntegrationsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32
		var v string

		httpRes, err := apiClient.AlertingIntegrationsApi.AlertingIntegrationsDelete(context.Background(), id, v).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertingIntegrationsApiService AlertingIntegrationsEdit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var v string

		httpRes, err := apiClient.AlertingIntegrationsApi.AlertingIntegrationsEdit(context.Background(), v).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertingIntegrationsApiService AlertingIntegrationsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alertingProfileId int32
		var v string

		resp, httpRes, err := apiClient.AlertingIntegrationsApi.AlertingIntegrationsList(context.Background(), alertingProfileId, v).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
